# Generated by Django 3.1.2 on 2020-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
